name: Monitor Cloudflare IPs

on:
  schedule:
    - cron: '*/15 * * * *'  # 每15分钟执行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  extract_ips:
    runs-on: ubuntu-latest
    
    steps:
      # 检出代码
      - name: Checkout repository
        uses: actions/checkout@v2

      # 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      # 提取网页 IP 地址
      - name: Extract IP addresses from the webpage
        run: |
          echo 'import requests' > extract_ips.py
          echo 'from bs4 import BeautifulSoup' >> extract_ips.py
          echo 'import re' >> extract_ips.py
          echo '' >> extract_ips.py
          echo 'url = "https://api.uouin.com/cloudflare.html"' >> extract_ips.py
          echo 'response = requests.get(url)' >> extract_ips.py
          echo 'html = response.text' >> extract_ips.py
          echo 'soup = BeautifulSoup(html, "html.parser")' >> extract_ips.py
          echo 'tbody = soup.find_all("tbody")' >> extract_ips.py
          echo 'ip_addresses = set()' >> extract_ips.py
          echo 'ip_pattern = r"\\b(?:\\d{1,3}\\.){3}\\d{1,3}\\b"' >> extract_ips.py
          echo 'for item in tbody:' >> extract_ips.py
          echo '    text = item.get_text()' >> extract_ips.py
          echo '    ips = re.findall(ip_pattern, text)' >> extract_ips.py
          echo '    ip_addresses.update(ips)' >> extract_ips.py
          echo 'formatted_ips = [f"{ip}:8443" for ip in ip_addresses]' >> extract_ips.py
          echo 'with open("CFIPS", "w") as f:' >> extract_ips.py
          echo '    f.write("\\n".join(formatted_ips))' >> extract_ips.py

          # 执行 Python 脚本
          python extract_ips.py

      # 将文件提交到 GitHub 仓库
      - name: Commit and push updated CFIPS file
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add CFIPS
          git commit -m "Update CFIPS"
          git push
