name: Auto Update CFIPS

on:
  schedule:
    - cron: '*/15 * * * *'  # 每15分钟执行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  update_cfips:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 允许直接推送修改

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main  # 直接操作 main 分支

      - name: Install curl
        run: |
          sudo apt-get update -y
          sudo apt-get install -y curl

      - name: Fetch and extract IPv4 addresses
        run: |
          # 抓取网页源代码并提取 IPv4 地址
          curl -s https://api.uouin.com/cloudflare.html | \
          grep -oP '\b(?:\d{1,3}\.){3}\d{1,3}\b' | \
          sort -u > ips.txt

          # 格式化为 ip:8443
          awk '{print $1":8443"}' ips.txt > CFIPS

      - name: Commit and push if changed
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          # 判断 CFIPS 文件是否有变化
          if git diff --quiet CFIPS; then
            echo "✅ 没有变化，跳过提交。"
            exit 0
          fi

          git add CFIPS
          git commit -m "Auto update CFIPS ($(date '+%Y-%m-%d %H:%M:%S'))"
          git push origin main
