name: Monitor Cloudflare IPs

on:
  schedule:
    - cron: '*/15 * * * *'  # 每15分钟执行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  extract_ips:
    runs-on: ubuntu-latest
    
    steps:
      # 检出代码
      - name: Checkout repository
        uses: actions/checkout@v2

      # 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      # 提取网页 IP 地址
      - name: Extract IP addresses from the webpage
        run: |
          import requests
          from bs4 import BeautifulSoup
          import re

          # 定义目标网址
          url = "https://api.uouin.com/cloudflare.html"
          
          # 获取网页内容
          response = requests.get(url)
          html = response.text

          # 使用 BeautifulSoup 解析网页
          soup = BeautifulSoup(html, "html.parser")

          # 查找 <tbody> 中的所有文本内容
          tbody = soup.find_all('tbody')
          
          ip_addresses = set()  # 使用 set 来避免重复的 IP 地址

          # 正则表达式匹配 IPv4 地址
          ip_pattern = r'\b(?:\d{1,3}\.){3}\d{1,3}\b'

          for item in tbody:
              text = item.get_text()
              ips = re.findall(ip_pattern, text)
              ip_addresses.update(ips)

          # 格式化 IP 地址为 ip:8443
          formatted_ips = [f"{ip}:8443" for ip in ip_addresses]

          # 将 IP 地址保存到文件中
          with open('CFIPS', 'w') as f:
              f.write("\n".join(formatted_ips))

      # 将文件提交到 GitHub 仓库
      - name: Commit and push updated CFIPS file
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add CFIPS
          git commit -m "Update CFIPS"
          git push
