name: Monitor IPs and Update CFIPS

on:
  schedule:
    - cron: '*/15 * * * *'  # 每15分钟执行一次
  workflow_dispatch:  # 也可以手动触发

jobs:
  monitor_ips:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq

      - name: Fetch webpage and extract IPv4 addresses
        id: fetch_ips
        run: |
          # Fetch the HTML source code of the page
          curl -s https://api.uouin.com/cloudflare.html | \
          # Use grep to find all the IPv4 addresses and remove duplicates
          grep -oP '\b(?:\d{1,3}\.){3}\d{1,3}\b' | \
          sort | uniq > ips.txt
        
      - name: Format IP addresses with port
        id: format_ips
        run: |
          # Format the IP addresses with port 8443
          awk '{print $1":8443"}' ips.txt > formatted_ips.txt

      - name: Update CFIPS file in the repository
        run: |
          # Create a new branch to update the CFIPS file
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git checkout -b update-ips
          
          # Add the new IPs to the CFIPS file
          echo -e "\n$(cat formatted_ips.txt)" >> CFIPS
          
          # Commit and push the changes
          git add CFIPS
          git commit -m "Update CFIPS with new IPs"
          git push --set-upstream origin update-ips

      - name: Create a pull request
        uses: peter-evans/create-pull-request@v4
        with:
          title: "Update CFIPS with new IPs"
          body: "This PR updates CFIPS with the latest IPs extracted from the webpage."
          head: update-ips
          base: main
