name: Auto Update Best IPs

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 * * * *"  # 每小时运行一次

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip requests

      - name: Run update script
        run: python .github/workflows/UpBestIP.py

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add BestIPs_v4 BestIPs_v6 BestProxyIPs || true
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Auto-update BestIPs (v4/v6/proxy)"
            git push
          fi
