name: 自动更新 BestIPs（增强版）

on:
  push:
    branches: [ main ]
    paths:
      - "BestIPs_v4"
      - "BestIPs_v6"
      - "BestProxyIPs"
  workflow_dispatch:  # 支持手动触发

jobs:
  update-bestips:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ 检出仓库代码
      - name: 检出代码
        uses: actions/checkout@v4

      # 2️⃣ 设置 Python 环境
      - name: 设置 Python 环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # 3️⃣ 安装依赖
      - name: 安装依赖
        run: pip install requests

      # 4️⃣ 运行 Cloudflare 更新脚本（打印添加和删除的 IP）
      - name: 更新 Cloudflare DNS
        run: python .github/workflows/UpBestIP.py
        env:
          CF_TOKENS: ${{ secrets.CF_TOKENS }}

      # 5️⃣ 自动 commit/push 更新的 IP 文件（仅在文件有变化时）
      - name: 提交更新的 IP 文件
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add BestIPs_v4 BestIPs_v6 BestProxyIPs || true

          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            TIMESTAMP=$(date +'%Y-%m-%d %H:%M:%S')
            git commit -m "Auto-update Best IPs at $TIMESTAMP [ci skip]"
            git push

      # 6️⃣ 可选：打印本次提交包含的文件列表
      - name: 打印本次提交文件
        if: success() && github.ref == 'refs/heads/main'
        run: |
          echo "本次提交的文件列表："
          git diff --name-only HEAD~1 HEAD
