name: Update CF-BestIPs-A
on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  update-ips:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update IPs
        run: |
          set -e

          retry() {
            local n=0
            local max=3
            local delay=5
            until "$@"; do
              n=$((n+1))
              if [ $n -ge $max ]; then
                echo "Command failed after $n attempts: $*"
                return 1
              fi
              echo "Retry $n/$max after $delay seconds..."
              sleep $delay
            done
          }

          IPS=$(retry curl -s -f --connect-timeout 10 --retry 2 'https://www.wetest.vip/api/cf2dns/get_cloudflare_ip?key=o1zrmHAF&type=v4' | \
                grep -Eo '([0-9]{1,3}\.){3}[0-9]{1,3}|([0-9a-fA-F:]+:+)+[0-9a-fA-F]+' | sort -u) || { echo "Error: failed to fetch or extract IPs"; exit 1; }

          [ -n "$IPS" ] || { echo "Error: IP list is empty"; exit 1; }

          echo "$IPS" | awk '{print $0":8443"}' > CF-BestIPs-A

          [ -s CF-BestIPs-A ] || { echo "Error: IP list is empty after processing"; exit 1; }

          git config user.name 'GitHub Actions'
          git config user.email 'actions@github.com'
          git add CF-BestIPs-A
          git commit -m "🤖 Update CF-BestIPs-A $(TZ=Asia/Shanghai date '+%Y-%m-%d %H:%M')" || true
          retry git pull --rebase origin main || { echo "Error: git pull failed"; exit 1; }
          retry git push origin main || { echo "Error: git push failed"; exit 1; }

          echo "Successfully updated CF-BestIPs-A"
        shell: /usr/bin/bash -e {0}
