name: Update Best IPs
on:
  schedule:
    - cron: '*/15 * * * *' # 每15分钟运行一次
  workflow_dispatch: # 支持手动触发

jobs:
  update-ips:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码库
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 获取完整历史记录以避免推送问题

      - name: 获取并更新 IP 地址
        run: |
          set -e # 遇到错误时退出

          # 获取网页内容并提取最多 10 个 IPv4 地址
          echo "正在获取网页内容..."
          if ! curl -s -f --connect-timeout 10 --retry 2 --retry-delay 5 'https://www.wetest.vip/page/cloudflare/address_v4.html' > webpage.html; then
            echo "错误：无法访问网页，可能由于网络问题或网页不可用。"
            exit 1
          fi

          # 提取 IPv4 地址
          echo "正在提取 IP 地址..."
          grep -Eo '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' webpage.html | \
          sort -u | head -n 10 | \
          sed 's/$/:8443/' > new_BestIPs.txt || {
            echo "错误：无法提取有效 IP 地址，可能网页内容无 IP 或格式不符。"
            rm -f webpage.html
            exit 1
          }

          # 检查 new_BestIPs.txt 是否为空
          if [ ! -s new_BestIPs.txt ]; then
            echo "错误：提取的 IP 列表为空，可能网页无有效 IP 地址。"
            rm -f webpage.html new_BestIPs.txt
            exit 1
          fi

          # 检查是否有变化
          if [ -f BestIPs ] && cmp -s new_BestIPs.txt BestIPs; then
            echo "IP 地址无变化，跳过更新。"
            rm -f webpage.html new_BestIPs.txt
            exit 0
          fi

          # 更新 BestIPs 文件
          echo "正在更新 BestIPs 文件..."
          mv new_BestIPs.txt BestIPs || {
            echo "错误：无法移动 new_BestIPs.txt 到 BestIPs。"
            rm -f webpage.html new_BestIPs.txt
            exit 1
          }

          # 配置 Git 并提交
          echo "正在提交更改..."
          git config user.name 'GitHub Actions'
          git config user.email 'actions@github.com'
          git add BestIPs || {
            echo "错误：无法添加 BestIPs 到 Git 索引。"
            rm -f webpage.html
            exit 1
          }
          git commit -m "自动更新BestIPs" || {
            echo "警告：无更改可提交，可能文件内容未变化。"
          }

          # 拉取并变基
          echo "正在执行 git pull --rebase..."
          if ! git pull --rebase origin main; then
            echo "错误：git pull --rebase 失败，可能存在冲突或网络问题。"
            exit 1
          fi

          # 推送更改
          echo "正在推送更改..."
          if ! git push origin main; then
            echo "错误：git push 失败，可能由于权限问题或远程分支冲突。"
            exit 1
          fi

          echo "成功更新并推送 BestIPs 文件。"
          rm -f webpage.html
        shell: /usr/bin/bash -e {0}
