name: Update Best IPs
on:
  schedule:
    - cron: '*/15 * * * *' # 每15分钟运行一次
  workflow_dispatch: # 支持手动触发

jobs:
  update-ips:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码库
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 获取完整历史记录以避免推送问题

      - name: 获取并更新 IP 地址
        run: |
          # 获取网页内容并提取最多 10 个 IPv4 地址
          curl -s 'https://www.wetest.vip/page/cloudflare/address_v4.html' | \
          grep -Eo '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | \
          sort -u | head -n 10 | \
          sed 's/$/:8443/' > new_BestIPs.txt

          # 检查是否有变化
          if [ -f BestIPs ] && cmp -s new_BestIPs.txt BestIPs; then
            echo "IP 地址无变化，跳过更新。"
            rm new_BestIPs.txt
            exit 0
          fi

          # 更新 BestIPs 文件
          mv new_BestIPs.txt BestIPs
          git config user.name 'GitHub Actions'
          git config user.email 'actions@github.com'
          git add BestIPs
          git pull --rebase origin main
          git diff --staged --quiet || (git commit -m "自动更新BestIPs" && git push origin main)
        shell: /usr/bin/bash -e {0}
```
