name: Update BestIPs


on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour at minute 0 (aligned for CST, UTC+8)
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write  # Grants write access for repository contents

jobs:
  sync-bestips:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Fetch and process content
        run: |
          curl -s https://ipdb.api.030101.xyz/?type=bestcf | \
          awk -F'#' '{print $1}' | \
          grep -Eo '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | \
          head -n 10 | \
          sed 's/$/:8443/' > new_BestIPs.txt

      - name: Check for content changes
        id: check
        run: |
          if ! cmp -s new_BestIPs.txt BestIPs; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Update and commit changes
        if: steps.check.outputs.changes == 'true'
        run: |
          mv new_BestIPs.txt BestIPs
          git config user.name 'GitHub Actions'
          git config user.email 'actions@github.com'
          git add BestIPs
          git commit -m "Automated update: Sync top 10 IPs with port 8843"
          git push origin main

      - name: Clean up
        if: always()
        run: rm -f new_BestIPs.txt
