name: Update BestIPs
on:
  schedule:
    - cron: '0,15,30,45 * * * *' # 每个整点开始的第0、15、30、45分钟运行
  workflow_dispatch: # 支持手动触发

jobs:
  update-ips:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码库
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 获取完整历史记录

      - name: 获取并更新 IP 地址
        run: |
          set -e
          # 获取网页内容并提取最多 10 个 IPv4 地址
          # 若需更换链接，修改以下 URL 即可，例如：'https://new.example.com/ip-list'
          curl -s -f --connect-timeout 10 --retry 2 'https://www.wetest.vip/page/cloudflare/address_v4.html' | \
          grep -Eo '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | \
          sort -u | head -n 10 | \
          sed 's/$/:8443/' > new_BestIPs.txt || {
            echo "错误：无法获取或提取 IP 地址"
            exit 1
          }

          # 检查 new_BestIPs.txt 是否为空
          [ -s new_BestIPs.txt ] || { echo "错误：IP 列表为空"; exit 1; }

          # 检查是否有变化
          [ -f BestIPs ] && cmp -s new_BestIPs.txt BestIPs && { echo "IP 地址无变化"; rm new_BestIPs.txt; exit 0; }

          # 更新文件并提交
          mv new_BestIPs.txt BestIPs || { echo "错误：无法更新 BestIPs 文件"; exit 1; }
          git config user.name 'GitHub Actions'
          git config user.email 'actions@github.com'
          git add BestIPs
          git commit -m "自动更新 BestIPs $(TZ=Asia/Shanghai date '+%Y-%m-%d %H:%M')" || true
          git pull --rebase origin main || { echo "错误：git pull --rebase 失败"; exit 1; }
          git push origin main || { echo "错误：git push 失败"; exit 1; }
          echo "成功更新 BestIPs"
        shell: /usr/bin/bash -e {0}
