name: Update BestIPs
on:
  schedule:
    - cron: '5,20,35,50 * * * *'
  workflow_dispatch: # 支持手动触发

jobs:
  update-ips:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码库
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 获取完整历史记录

      - name: 获取并更新 IP 地址
        run: |
          set -e
          # 获取网页内容并提取所有 IPv4 地址
          # 若需更换链接，修改以下 URL 即可，例如：'https://new.example.com/ip-list'
          curl -s -f --connect-timeout 10 --retry 2 'https://www.wetest.vip/page/cloudflare/address_v4.html' | \
          grep -Eo '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | \
          sort -u > temp_ips.txt || {
            echo "错误：无法获取或提取 IP 地址"
            exit 1
          }

          # 检查 temp_ips.txt 是否为空
          [ -s temp_ips.txt ] || { echo "错误：IP 列表为空"; exit 1; }

          # 处理每个 IP：添加端口并查询国家代码
          > BestIPs  # 清空 BestIPs 文件
          while IFS= read -r ip; do
            # 添加端口
            ip_port="${ip}:8443"
            
            # 查询国家代码（使用 ip-api.com 免费 API）
            country_code=$(curl -s --connect-timeout 5 --retry 1 "http://ip-api.com/json/${ip}?fields=countryCode" | grep -o '"countryCode":"[^"]*"' | cut -d'"' -f4 || echo "")
            
            # 如果查询成功且国家代码非空，则添加 #国家代码 IP
            if [ -n "$country_code" ] && [ "$country_code" != "N/A" ]; then
              echo "${ip_port} #${country_code}${ip}" >> BestIPs
            else
              echo "${ip_port}" >> BestIPs
            fi
          done < temp_ips.txt

          # 移除临时文件
          rm temp_ips.txt

          # 检查 BestIPs 是否为空
          [ -s BestIPs ] || { echo "错误：IP 列表为空"; exit 1; }

          # 提交更新
          git config user.name 'GitHub Actions'
          git config user.email 'actions@github.com'
          git add BestIPs
          git commit -m "自动更新 BestIPs $(TZ=Asia/Shanghai date '+%Y-%m-%d %H:%M')" || true
          git pull --rebase origin main || { echo "错误：git pull --rebase 失败"; exit 1; }
          git push origin main || { echo "错误：git push 失败"; exit 1; }
          echo "成功更新 BestIPs"
        shell: /usr/bin/bash -e {0}
