name: Update BestProxyIPs

on:
  schedule:
    - cron: '0 */1 * * *'  # Run every 1 hours
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-ips:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码库
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 获取完整历史记录

      - name: 获取并更新 IP 地址
        run: |
          set -e
          # 获取网页内容并提取 IPv4 地址
          curl -s -f --connect-timeout 10 --retry 2 'https://ipdb.030101.xyz/bestproxy/' | \
          grep -Eo '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | \
          sort -u | \
          sed 's/$/:443/' > temp_ips.txt || {
            echo "错误：无法获取或提取 IP 地址"
            exit 1
          }

          # 检查 temp_ips.txt 是否为空
          [ -s temp_ips.txt ] || { echo "错误：IP 列表为空"; exit 1; }

          # 检查是否有变化
          [ -f BestProxyIPs ] && cmp -s temp_ips.txt BestProxyIPs && { echo "IP 地址无变化"; rm temp_ips.txt; exit 0; }

          # 更新文件并提交
          mv temp_ips.txt BestProxyIPs || { echo "错误：无法更新 BestProxyIPs 文件"; exit 1; }
          git config user.name 'GitHub Actions'
          git config user.email 'actions@github.com'
          git add BestProxyIPs
          git commit -m "自动更新 BestProxyIPs $(TZ=Asia/Shanghai date '+%Y-%m-%d %H:%M')" || true
          git pull --rebase origin main || { echo "错误：git pull --rebase 失败"; exit 1; }
          git push origin main || { echo "错误：git push 失败"; exit 1; }
          echo "成功更新 BestProxyIPs"
        shell: /usr/bin/bash -e {0}noreply.github.com'
          git add BestProxyIPs
          git commit -m "Update BestProxyIPs with latest IPs" || echo "No changes to commit"
          git push
